name: char_score_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.3
  - numpy=2.3
  - matplotlib=3.10
  - seaborn=0.13
  - plotly=6.0
  - ipywidgets=8.1
  - ipython=9.7
  - jupyter=1.1
  - scikit-learn=1.7
  - scipy=1.16
  - pingouin=0.5
  - finaltools
