name: char_score_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - ipywidgets
  - ipython
  - notebook
  - pip
  - pip:
      - random2
